leverage:
  EURUSD: 30
  GBPUSD: 30
  USDJPY: 30
  USDCHF: 30
  AUDUSD: 20
  NZDUSD: 20
  USDCAD: 30
  EURJPY: 30
  EURGBP: 30
  EURCHF: 30
  AUDJPY: 20
  CHFJPY: 30
  GBPJPY: 30
  GBPCHF: 30
  AUDCAD: 20
  EURCAD: 30
  AUDNZD: 20

spread:
  EURUSD: 1
  GBPUSD: 1
  USDJPY: 1
  USDCHF: 1
  AUDUSD: 1
  NZDUSD: 1
  USDCAD: 1
  EURJPY: 1
  EURGBP: 1
  EURCHF: 2
  AUDJPY: 1
  CHFJPY: 2
  GBPJPY: 2
  GBPCHF: 2
  AUDCAD: 1
  EURCAD: 1
  AUDNZD: 2