symbol:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "USDCHF"
  - "USDCAD"
  - "AUDUSD"
  - "NZDUSD"
  - "EURGBP"
  - "EURJPY"
  - "EURCHF"
  - "GBPCHF"
  - "GBPJPY"
  - "AUDCAD"
  - "EURCAD"
  - "AUDNZD"
  - "AUDJPY"
  - "CHFJPY"
time_frame:
  - "Minute5"
  - "Minute15"
num_indicators: 
  - 12
  - 16
num_selectors:
  - 8
  - 12
h_layers:
  -
    - 16
    - 16
weight_decay:
  - 0.0001
  - 0.0005
  - 0.001
  - 0.005
  - 0.01
  - 0.03
  - 0.05
  - 0.1
cuda: false
pop_size: 8
num_epochs: 100
tourn_size: 2
elitism: 1
cross_rate:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
ind_mut_rate:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
sel_mut_rate:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
params_mut_rate:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
model_mut_σ:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
  - 0.15
  - 0.2
  - 0.3
lr:
  - 0.005
  - 0.01
  - 0.015
  - 0.02
  - 0.025
  - 0.03
  - 0.035
  - 0.04
  - 0.045
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
  - 0.15
  - 0.2
  - 0.3
fit_disc_rate: 0.999
fit_cv_coef: 0.5
sim_date_from: 2021-02-27T00:00:00
sim_date_to: 2021-05-01T00:00:00
init_balance: 100
acc_curr: "EUR"
risk: 0.02
commission: 4.5e-5
hyp_opt-iter: 100
log_name: "strat_creat_A"
log_every: 10
desc: "All the pairs, Minute5-Minute15, 03/2021-04/2021, low balance: 100€"
